Adjust AggressiveUnroll to fix type error during unroll (#593)
I'm not sure what was causing the error but rearranging the passes with
the help of @weinbe58 fixed the problem.

For context, this was the error.  I did not find a MWE.
```python
Traceback (most recent call last):
  File "my_script.py", line 49, in compile_to_stim
    PhysicalAndSquinToStim(main.dialects, no_raise=no_raise)(main)
  File "site-packages/kirin/passes/abc.py", line 30, in __call__
    result = self.unsafe_run(mt)
  File "squin_and_to_stim.py", line 99, in unsafe_run
    .unsafe_run(mt)
  File "site-packages/bloqade/rewrite/passes/canonicalize_ilist.py", line 29, in unsafe_run
    ).rewrite(mt.code)
  File "site-packages/kirin/rewrite/fixpoint.py", line 24, in rewrite
    result = self.rule.rewrite(node)
  File "site-packages/kirin/rewrite/walk.py", line 40, in rewrite
    result = self.rule.rewrite(subnode)
  File "site-packages/kirin/rewrite/chain.py", line 29, in rewrite
    result = rule.rewrite(node)
  File "site-packages/kirin/rewrite/abc.py", line 38, in rewrite
    return self.rewrite_Statement(cast(Statement, node))
  File "site-packages/kirin/dialects/ilist/rewrite/flatten_add.py", line 49, in rewrite_Statement
    assert isinstance(rhs_type := rhs.type, types.Generic), "Impossible"
AssertionError: Impossible
```

---------

Co-authored-by: Phillip Weinberg <pweinberg@quera.com>